sprint 13
LanaLesana/java-shareit pull request #1
Opened 2023-10-09 01:07 UTC by LanaLesana

2023-10-09 18:45 UTC, z8q requested changes

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/booking/BookingStorage.java
> +package ru.practicum.shareit.storage.booking;
Внутри storage все равно происходит разбивка на booking, item, user, request.
Можно было бы сразу в верхнеуровневые пакеты вынести storage классы)

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    @Autowired
Без  аннотации Autowired  `Dependency Injection` все равно будет происходить.
https://docs.spring.io/spring-boot/docs/current/reference/html/using.html#using.spring-beans-and-dependency-injection

Тут можно посмотреть, как работает с одним конструктором и с несколькими

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/User.java
> +    @Email
В  dto тоже есть валидация этого поля.
Рекомендую разделить функционал дто и сущности.
Дто использовать на приеме в контроллере и в логике программы, а сущность использовать только для хранения. В последующих домашках станет понятнее. Сущность будет описывать формат таблицы и зависимости между другими сущностями.

Это все к тому, что валидацию полей можно полностью перенести в dto (аннотации notNull, notBlank, email и т.д.)
И конвертировать из дто в сущность прямо перед сохранением.
Соответственно при получении сущности из хранилища сразу конвертировать в дто и в логике программы использовать только дто

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    public static UserDto toUserDto(User user) {
Этот метод можно вынести в отдельный класс-маппер.
Возможно обратное действие тоже будет нужно – dtoToUser.

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/model/Item.java
>  package ru.practicum.shareit.item.model;
Сущность Item находится  в ru.practicum.shareit.item.model
User в ru.practicum.shareit.user
Можно привести к общему виду, для User тоже создать model

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<Item> getAllItemsByOwner(@RequestHeader("X-Sharer-User-Id") int sharerUserId) {
Тут и в методе searchItem  стоит возвращать список dto

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/item/ItemService.java
> +    UserStorage userStorage;
Поля storage классов стоит сделать private final.
Над классом использовать аннотацию RequiredArgsConstructor
Autowired будет не нужен

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/user/InMemoryUserStorage.java
> +        return allUsersList;
Можно попробовать такую конструкцию  return new ArrayList<>(userHashMap.values());

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/user/InMemoryUserStorage.java
> +        List<User> users = getAllUsers();
Возможно будет интересно применить
```
List<String> emails  = userHashMap.values().stream()
.map(user -> user.getEmail()).collect(Collectors.toSet());
```

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/user/UserService.java
> +    UserStorage userStorage;
Тут рекомендация как с ItemService

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/user/UserService.java
> +        System.out.println("Add user Service after valid");
В консоль выводить не совсем правильно.
Нужно логировать

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +//    @GetMapping("/films")
Закомментированные блоки стоит убирать

2023-10-09 18:45 UTC, z8q commented on src/main/java/ru/practicum/shareit/storage/item/ItemService.java
> +@Slf4j
В некоторых местах используется аннотация, в некоторых LoggerFactory. Стоит привести к одному виду

2023-10-12 03:23 UTC, LanaLesana commented on src/main/java/ru/practicum/shareit/storage/item/ItemService.java
> +    UserStorage userStorage;
Так всё сломалось

2023-10-12 17:18 UTC, z8q approved these changes

2023-10-12 17:18 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserService.java
> +@RequiredArgsConstructor
Тут нужно учесть что RequiredArgsConstructor создает конструктор для final полей.
Из доки:
Generates a constructor with required arguments. Required arguments are final fields and fields with constraints such as @NonNull.

2024-01-23 15:18 UTC, merged