Add bookings
LanaLesana/java-shareit pull request #2
Opened 2024-01-23 15:16 UTC by LanaLesana

2024-01-24 16:17 UTC, z8q requested changes

2024-01-24 16:17 UTC, z8q commented on src/main/resources/schema.sql
> +        request_id VARCHAR(255)
owner_id это будет foreignKey от user-а
request_id - foreignKey от requests

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    JpaItemRepository jpaItemRepository;
Над классом используется `@RequiredArgsConstructor` - создает конструктор для final полей.
Нам надо пометить все поля private final. Тогда можно будет еще убрать `@Autowired` с каждого поля

Еще вопрос, стоит ли создавать отдельный ItemStorage. Подумал, что мы только через этот класс будем обращаться к jpaItemRepository. Но здесь в сервисе есть и itemStorage, и jpaItemRepository.
Может быть тогда логику из itemStorage перенести сюда

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public UserDto addUser(UserDto userDto) {
При попытке добавления дубля юзера приходит ошибка 409 без описания. Можно было бы обрабатывать и возвращать объект с сообщением, что пользователь уже есть

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserServiceImpl.java
> +    public UserDto updateUser(UserDto userDto, int userId) {
Удается обновить данные пользователя на пустые
PATCH http://localhost:8080/users/1
```JSON
{
	"name": "",
	"email": ""
}
```

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    public ItemDto addItem(ItemDto itemDto, int sharerUserId) {
При добавлении вещи с несуществующим X-Sharer-User-Id получаем 404. Можно было бы передавать сообщение, что пользователь не найден

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingController.java
> +    public Booking addItem(@RequestBody BookingDto bookingDto, @RequestHeader("X-Sharer-User-Id") int bookerId) {
При добавлении букинга на прошлые даты получаю 400. Стоит еще присылать описание ошибки.
Если указать X-Sharer-User-Id владельца, то приходит 404, можно было бы тоже еще прислать описание. Если указать несуществующий X-Sharer-User-Id - тоже просто 404.

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/validation/BookingValidation.java
> +        if (booking.getItem().getOwner().getId() != idUser) {
Тут упадем с NullPointerException, если в запросе будет несуществующий id букинга:
patch http://localhost:8080/bookings/1234?approved=true

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +        LocalDateTime start = bookingStorage.getBookingById(itemId).getStart();
Здесь упадем с NullPointerException при следующем запросе:
POST http://localhost:8080/items/11123/comment
несуществующая вещь

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/db/ItemStorage.java
> +                bookingConciseNext = BookingConcise.builder().id(lastBooking.getId())
в 142-й строке (lastBooking != null || nextBooking != null) если хотя бы какое-то бронирование не null, то сможем зайти в этот блок. Но например в строке 145 упадем с NullPointerException, если lastBooking == null,
в 143-й – если nextBooking == null


после работы с сервисом, методы get /items /items{id} перестают работать из-за этого

2024-01-24 16:17 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/db/JpaItemRepository.java
> +    List<Item> search(String text);
Если к аргументу добавить аннотацию Param, то в query можно будет вместо ?1 писать так:
concat('%', :text, '%')

Сам метод такой:
List search(@param("text") String text);

2024-01-25 13:58 UTC, LanaLesana commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +    JpaItemRepository jpaItemRepository;
А можно оставить itemStorage? А то ItemServiceImpl и так очень массивный, не много ли кода для одного класса будет?

2024-01-25 17:44 UTC, z8q approved these changes

2024-01-25 17:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
>      UserDtoMapper userDtoMapper = new UserDtoMapper();
маппер тоже можно сделать приватным

2024-01-25 17:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +    JpaUserRepository userRepository;
Тут с Autowired можно сделать также, как и в ItemService

2024-01-25 17:44 UTC, z8q commented on src/main/java/ru/practicum/shareit/booking/db/JpaBookingRepository.java
> +    Booking findFirstByItemIdAndStatusAndStartIsAfterOrStartEqualsOrderByStart(Integer id, Status status, LocalDateTime localDateTime,
Когда методы становятся слишком длинными, бывает проще переписать с использованием Query

2024-02-06 14:02 UTC, merged